Repository matching-manager/matching-manager, pull requests merged in 2023-10, with the labels that each got.

#2 [Test] : test용 커밋
  app/src/main/java/com/example/matching_manager/ui/home/HomeFragment.kt
Labels: 🎨 Design

#4 [fix] homefragment
  app/src/main/java/com/example/matching_manager/ui/home/HomeFragment.kt
Labels: 🩺 Fix

#7 [Merge] test4
  app/src/main/java/com/example/matching_manager/ui/home/HomeFragment.kt
Labels: 🛠 Feat

#13 Feature/viewpager
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/matching_manager/ui/MainActivity.kt
  app/src/main/java/com/example/matching_manager/ui/calender/CalendarFragment.kt
  app/src/main/java/com/example/matching_manager/ui/home/HomeFragment.kt
  app/src/main/java/com/example/matching_manager/ui/main/MainActivity.kt
  app/src/main/java/com/example/matching_manager/ui/main/MainTabs.kt
  app/src/main/java/com/example/matching_manager/ui/main/MainViewPagerAdapter.kt
  app/src/main/java/com/example/matching_manager/ui/match/MatchFragment.kt
  app/src/main/java/com/example/matching_manager/ui/my/MyFragment.kt
  app/src/main/java/com/example/matching_manager/ui/team/TeamFragment.kt
  app/src/main/res/color/tab_color_selector.xml
  app/src/main/res/drawable/main_tablayout_background.xml
  app/src/main/res/layout/main_activity.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 🛠 Feat

#15 [Merge] retrofit을 사용한 API 받아오기 및 MVVM Layer(Data, Domain, Ui) 구성
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/matching_manager/data/model/ArenaResponse.kt
  app/src/main/java/com/example/matching_manager/data/remote/ArenaRemoteDataSource.kt
  app/src/main/java/com/example/matching_manager/data/repository/ArenaRepositoryImpl.kt
  app/src/main/java/com/example/matching_manager/domain/model/ArenaEntity.kt
  app/src/main/java/com/example/matching_manager/domain/model/modelMapper.kt
  app/src/main/java/com/example/matching_manager/domain/repository/ArenaRepository.kt
  app/src/main/java/com/example/matching_manager/domain/usecase/GetArenaInfoUseCase.kt
  app/src/main/java/com/example/matching_manager/retrofit/AuthorizationInterceptor.kt
  app/src/main/java/com/example/matching_manager/retrofit/RetrofitClient.kt
  app/src/main/java/com/example/matching_manager/ui/home/arena/ArenaActivity.kt
  app/src/main/java/com/example/matching_manager/ui/home/arena/ArenaModel.kt
  app/src/main/java/com/example/matching_manager/ui/home/arena/ArenaViewModel.kt
  app/src/main/java/com/example/matching_manager/ui/home/arena/ArenaViewModelFactory.kt
  app/src/main/res/layout/arena_activity.xml
  app/src/main/res/values/kakao_api_key.xml
  app/src/main/res/values/strings.xml
Labels: 📬 API, 🛠 Feat

#17 [Merge] Feature/team fragment
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/matching_manager/ui/team/TeamDetailActivity.kt
  app/src/main/java/com/example/matching_manager/ui/team/TeamFragment.kt
  app/src/main/java/com/example/matching_manager/ui/team/TeamListAdapter.kt
  app/src/main/java/com/example/matching_manager/ui/team/TeamModel.kt
  app/src/main/java/com/example/matching_manager/ui/team/TeamTab.kt
  app/src/main/java/com/example/matching_manager/ui/team/TeamViewPagerAdapter.kt
  app/src/main/java/com/example/matching_manager/ui/team/menu/MyTeamFragment.kt
  app/src/main/java/com/example/matching_manager/ui/team/menu/RecruitmentFragment.kt
  app/src/main/java/com/example/matching_manager/ui/team/menu/TeamViewModel.kt
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/ic_bad_manner.xml
  app/src/main/res/drawable/ic_bodyguard.xml
  app/src/main/res/drawable/ic_good_manner.xml
  app/src/main/res/drawable/ic_people.xml
  app/src/main/res/drawable/ic_right.xml
  app/src/main/res/layout/activity_team_list_adapter.xml
  app/src/main/res/layout/activity_team_view_model.xml
  app/src/main/res/layout/item_team.xml
  app/src/main/res/layout/team__myteam_fragment.xml
  app/src/main/res/layout/team_detail_activity.xml
  app/src/main/res/layout/team_fragment.xml
  app/src/main/res/layout/team_recruitment_fragment.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/style.xml
Labels: 🛠 Feat

#19 [Merge] Home_Fragment ui 작업
  app/src/main/res/drawable/ic_back2.xml
  app/src/main/res/drawable/ic_badminton.xml
  app/src/main/res/drawable/ic_basketball.xml
  app/src/main/res/drawable/ic_bell.xml
  app/src/main/res/drawable/ic_bowling.xml
  app/src/main/res/drawable/ic_bowling1.xml
  app/src/main/res/drawable/ic_exercise.xml
  app/src/main/res/drawable/ic_futsal.xml
  app/src/main/res/drawable/ic_letter.xml
  app/src/main/res/drawable/ic_runner.xml
  app/src/main/res/drawable/ic_soccer.xml
  app/src/main/res/layout/home_alram.xml
  app/src/main/res/layout/home_fragment.xml
Labels: 🎨 Design

#20 [Merge] : Match Fragment 기본 구성 및 Match Detail Activity 연결
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/matching_manager/ui/match/MatchAdapter.kt
  app/src/main/java/com/example/matching_manager/ui/match/MatchCategory.kt
  app/src/main/java/com/example/matching_manager/ui/match/MatchData.kt
  app/src/main/java/com/example/matching_manager/ui/match/MatchDetailActivity.kt
  app/src/main/java/com/example/matching_manager/ui/match/MatchFragment.kt
  app/src/main/res/drawable/ic_chat.xml
  app/src/main/res/drawable/ic_eye.xml
  app/src/main/res/drawable/shape_item_match.xml
  app/src/main/res/drawable/sonny.png
  app/src/main/res/layout/match_category.xml
  app/src/main/res/layout/match_detail_activity.xml
  app/src/main/res/layout/match_fragment.xml
  app/src/main/res/layout/match_item.xml
  app/src/main/res/values/strings.xml
Labels: 🎨 Design, 🛠 Feat

#24 [Merge] ViewModel에서 Api 데이터 요청 및 매핑 + ArenaActivity Ui
  app/build.gradle
  app/src/main/java/com/example/matching_manager/data/model/ArenaResponse.kt
  app/src/main/java/com/example/matching_manager/data/remote/ArenaRemoteDataSource.kt
  app/src/main/java/com/example/matching_manager/domain/model/ArenaEntity.kt
  app/src/main/java/com/example/matching_manager/domain/repository/ArenaRepository.kt
  app/src/main/java/com/example/matching_manager/domain/usecase/GetArenaInfoUseCase.kt
  app/src/main/java/com/example/matching_manager/ui/home/HomeFragment.kt
  app/src/main/java/com/example/matching_manager/ui/home/arena/ArenaActivity.kt
  app/src/main/java/com/example/matching_manager/ui/home/arena/ArenaListAdapter.kt
  app/src/main/java/com/example/matching_manager/ui/home/arena/ArenaModel.kt
  app/src/main/java/com/example/matching_manager/ui/home/arena/ArenaViewModel.kt
  app/src/main/res/drawable/common_gradient_background.xml
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/ic_badminton.xml
  app/src/main/res/drawable/ic_basketball.xml
  app/src/main/res/drawable/ic_bowling.xml
  app/src/main/res/drawable/ic_futsal.xml
  app/src/main/res/drawable/ic_soccer.xml
  app/src/main/res/layout/arena_activity.xml
  app/src/main/res/layout/arena_recyclerview_item.xml
  app/src/main/res/values/strings.xml
Labels: 📬 API, 🎨 Design, 🛠 Feat

#26 [Merge] homefragment UI
  app/src/main/res/drawable/ic_profile.xml
  app/src/main/res/layout/my_fragment.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 🎨 Design

#28 [Merge] 입력한 주소의 위도경도 받아와 API 통신
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/matching_manager/data/model/ArenaResponse.kt
  app/src/main/java/com/example/matching_manager/data/remote/ArenaRemoteDataSource.kt
  app/src/main/java/com/example/matching_manager/data/repository/ArenaRepositoryImpl.kt
  app/src/main/java/com/example/matching_manager/domain/model/ArenaEntity.kt
  app/src/main/java/com/example/matching_manager/domain/model/modelMapper.kt
  app/src/main/java/com/example/matching_manager/domain/usecase/GetArenaInfoUseCase.kt
  app/src/main/java/com/example/matching_manager/retrofit/AuthorizationInterceptor.kt
  app/src/main/java/com/example/matching_manager/retrofit/RetrofitClient.kt
  app/src/main/java/com/example/matching_manager/ui/home/HomeFragment.kt
  app/src/main/java/com/example/matching_manager/ui/home/arena/ArenaActivity.kt
  app/src/main/java/com/example/matching_manager/ui/home/arena/ArenaListAdapter.kt
  app/src/main/java/com/example/matching_manager/ui/home/arena/ArenaViewModel.kt
  app/src/main/java/com/example/matching_manager/ui/home/arena/ArenaViewModelFactory.kt
  app/src/main/java/com/example/matching_manager/util/Utils.kt
  app/src/main/res/layout/arena_activity.xml
  app/src/main/res/values/kakao_api_key.xml
Labels: 🛠 Feat

#31 [Merge] team fragment spinner 구현
  app/build.gradle
  app/src/main/java/com/example/matching_manager/ui/team/TeamAddActivity.kt
  app/src/main/java/com/example/matching_manager/ui/team/TeamCalender.kt
  app/src/main/res/drawable/button_off.xml
  app/src/main/res/drawable/button_on.xml
  app/src/main/res/drawable/toggle_selector.xml
  app/src/main/res/layout/age_picker.xml
  app/src/main/res/layout/team_add_activity.xml
  app/src/main/res/layout/team_calender.xml
  app/src/main/res/layout/team_detail_activity.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/string_area.xml
  app/src/main/res/values/string_level.xml
  app/src/main/res/values/string_time.xml
  app/src/main/res/values/string_type.xml
  app/src/main/res/values/strings.xml
Labels: 🎨 Design, 🛠 Feat

#33 [Merge] 브런치 변경을 위한 Merge
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/matching_manager/ui/my/Image.kt
  app/src/main/java/com/example/matching_manager/ui/my/MyFileDialog.kt
  app/src/main/java/com/example/matching_manager/ui/my/MyFragment.kt
  app/src/main/java/com/example/matching_manager/ui/my/MyViewModel.kt
  app/src/main/res/layout/dialog_edit.xml
  app/src/main/res/layout/home_fragment.xml
Labels: 🎨 Design

#38 [Merge] : MVVM을 위한 data layer 변경
  app/src/main/java/com/example/matching_manager/ui/match/MatchFragment.kt
  app/src/main/java/com/example/matching_manager/ui/match/MatchListAdapter.kt
  app/src/main/java/com/example/matching_manager/ui/match/MatchRepository.kt
  app/src/main/java/com/example/matching_manager/ui/match/MatchRepositoryImpl.kt
  app/src/main/java/com/example/matching_manager/ui/match/MatchViewModel.kt
  app/src/main/java/com/example/matching_manager/ui/match/MatchViewModelFactory.kt
Labels: ♻ Refactor

#41 [Merge] : Arena detail 작업
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/matching_manager/ui/home/HomeFragment.kt
  app/src/main/java/com/example/matching_manager/ui/home/arena/ArenaActivity.kt
  app/src/main/java/com/example/matching_manager/ui/home/arena/ArenaListAdapter.kt
  app/src/main/java/com/example/matching_manager/ui/home/arena/ArenaViewModel.kt
  app/src/main/java/com/example/matching_manager/ui/home/arena/detail_dialog/ArenaDetailFragment.kt
  app/src/main/java/com/example/matching_manager/ui/home/arena/detail_dialog/ArenaDetailViewModel.kt
  app/src/main/java/com/example/matching_manager/util/Utils.kt
  app/src/main/res/drawable/btn_background_green_fill.xml
  app/src/main/res/drawable/btn_background_green_stroke.xml
  app/src/main/res/drawable/btn_background_white.xml
  app/src/main/res/drawable/dialog_radius_background.xml
  app/src/main/res/drawable/ic_call.xml
  app/src/main/res/layout/activity_team_list_adapter.xml
  app/src/main/res/layout/activity_team_view_model.xml
  app/src/main/res/layout/arena_detail_fragment.xml
  app/src/main/res/layout/home_fragment.xml
  app/src/main/res/layout/match_detail_activity.xml
  app/src/main/res/layout/team_add_activity.xml
  app/src/main/res/layout/team_detail_activity.xml
  app/src/main/res/values/strings.xml
Labels: 🎨 Design, 🛠 Feat

#42 [Merge] gallery 기능 추가
  app/src/main/java/com/example/matching_manager/ui/my/MyFileDialog.kt
  app/src/main/java/com/example/matching_manager/ui/my/MyFragment.kt
  app/src/main/res/drawable/ic_nickname.xml
  app/src/main/res/layout/dialog_edit.xml
  app/src/main/res/layout/my_fragment.xml
Labels: 🛠 Feat

#45 [Merge]Feature/team fragment
  app/build.gradle
  app/src/main/java/com/example/matching_manager/ui/match/MatchDetailActivity.kt
  app/src/main/java/com/example/matching_manager/ui/team/TeamAddActivity.kt
  app/src/main/java/com/example/matching_manager/ui/team/TeamDetailActivity.kt
  app/src/main/java/com/example/matching_manager/ui/team/TeamFragment.kt
  app/src/main/java/com/example/matching_manager/ui/team/TeamItem.kt
  app/src/main/java/com/example/matching_manager/ui/team/TeamListAdapter.kt
  app/src/main/java/com/example/matching_manager/ui/team/bottomsheet/TeamAddCategory.kt
  app/src/main/java/com/example/matching_manager/ui/team/bottomsheet/TeamAge.kt
  app/src/main/java/com/example/matching_manager/ui/team/bottomsheet/TeamCalender.kt
  app/src/main/java/com/example/matching_manager/ui/team/bottomsheet/TeamFilterCategory.kt
  app/src/main/java/com/example/matching_manager/ui/team/bottomsheet/TeamNumber.kt
  app/src/main/java/com/example/matching_manager/ui/team/mdoel/TeamModel.kt
  app/src/main/java/com/example/matching_manager/ui/team/view/TeamSharedViewModel.kt
  app/src/main/java/com/example/matching_manager/ui/team/view/TeamViewModel.kt
  app/src/main/res/layout/match_detail_activity.xml
  app/src/main/res/layout/match_writing_activity.xml
  app/src/main/res/layout/team_add_activity.xml
  app/src/main/res/layout/team_age.xml
  app/src/main/res/layout/team_calender.xml
  app/src/main/res/layout/team_detail_activity.xml
  app/src/main/res/layout/team_item.xml
  app/src/main/res/layout/team_number.xml
  app/src/main/res/layout/team_unknown_item.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/strings.xml
Labels: 🛠 Feat

#49 Feture/team add page
  app/build.gradle
  app/src/main/java/com/example/matching_manager/ui/team/TeamAddActivity.kt
  app/src/main/java/com/example/matching_manager/ui/team/TeamAddType.kt
  app/src/main/java/com/example/matching_manager/ui/team/TeamDetailActivity.kt
  app/src/main/java/com/example/matching_manager/ui/team/TeamFragment.kt
  app/src/main/java/com/example/matching_manager/ui/team/TeamItem.kt
  app/src/main/java/com/example/matching_manager/ui/team/TeamListAdapter.kt
  app/src/main/java/com/example/matching_manager/ui/team/bottomsheet/TeamAddCategory.kt
  app/src/main/java/com/example/matching_manager/ui/team/bottomsheet/TeamAge.kt
  app/src/main/java/com/example/matching_manager/ui/team/bottomsheet/TeamNumber.kt
  app/src/main/java/com/example/matching_manager/ui/team/view/TeamSharedViewModel.kt
  app/src/main/java/com/example/matching_manager/ui/team/view/TeamViewModel.kt
  app/src/main/res/layout/match_detail_activity.xml
  app/src/main/res/layout/team_add_activity.xml
  app/src/main/res/values/strings.xml
Labels: 🎨 Design, 🛠 Feat

#51 [MERGE]Refactoring/my code
  app/src/main/java/com/example/matching_manager/ui/match/MatchDetailActivity.kt
  app/src/main/java/com/example/matching_manager/ui/team/TeamAddActivity.kt
  app/src/main/java/com/example/matching_manager/ui/team/TeamDetailActivity.kt
  app/src/main/java/com/example/matching_manager/ui/team/TeamFragment.kt
  app/src/main/java/com/example/matching_manager/ui/team/TeamItem.kt
  app/src/main/java/com/example/matching_manager/ui/team/TeamListAdapter.kt
  app/src/main/java/com/example/matching_manager/ui/team/view/TeamViewModel.kt
  app/src/main/res/layout/team_fragment.xml
  app/src/main/res/values/string_type.xml
  app/src/main/res/values/strings.xml
Labels: ♻ Refactor

#53 [Merge] google login 연동
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/matching_manager/ui/my/MyFragment.kt
  app/src/main/java/com/example/matching_manager/ui/signin/SignInActivity.kt
  app/src/main/java/com/example/matching_manager/ui/signin/SignInFragment.kt
  app/src/main/res/drawable/ic_google_logo.xml
  app/src/main/res/layout/match_detail_activity.xml
  app/src/main/res/layout/my_fragment.xml
  app/src/main/res/layout/sign_in_activity.xml
  app/src/main/res/layout/sign_in_fragment.xml
  app/src/main/res/layout/sign_up_fragment.xml
  app/src/main/res/values/strings.xml
Labels: 🛠 Feat

#55 [Marge] FCM(Background,Forground) SharedPreference
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/matching_manager/data/repository/ArenaRepositoryImpl.kt
  app/src/main/java/com/example/matching_manager/data/repository/SharedPreferenceRepositoryImpl.kt
  app/src/main/java/com/example/matching_manager/domain/repository/SharedPreferenceRepository.kt
  app/src/main/java/com/example/matching_manager/domain/usecase/sharedpreference/LoadFcmDataUseCase.kt
  app/src/main/java/com/example/matching_manager/domain/usecase/sharedpreference/SaveFcmDataUseCase.kt
  app/src/main/java/com/example/matching_manager/fcm/FcmActivity.kt
  app/src/main/java/com/example/matching_manager/fcm/FcmViewModel.kt
  app/src/main/java/com/example/matching_manager/fcm/FcmViewModelFactory.kt
  app/src/main/java/com/example/matching_manager/fcm/MyFirebaseMessagingService.kt
  app/src/main/java/com/example/matching_manager/fcm/MyWorker.kt
  app/src/main/java/com/example/matching_manager/ui/home/HomeFragment.kt
  app/src/main/java/com/example/matching_manager/ui/home/alarm/AlarmActivity.kt
  app/src/main/java/com/example/matching_manager/ui/home/alarm/AlarmListAdapter.kt
  app/src/main/java/com/example/matching_manager/ui/home/alarm/AlarmModel.kt
  app/src/main/java/com/example/matching_manager/ui/home/alarm/AlarmViewModel.kt
  app/src/main/java/com/example/matching_manager/ui/home/alarm/AlarmViewModelFactory.kt
  app/src/main/java/com/example/matching_manager/ui/home/alram/AlramActivity.kt
  app/src/main/java/com/example/matching_manager/ui/main/MainActivity.kt
  app/src/main/java/com/example/matching_manager/util/Utils.kt
  app/src/main/res/layout/alarm_activity.xml
  app/src/main/res/layout/alarm_recyclerview_item.xml
  app/src/main/res/layout/alram_activity.xml
  app/src/main/res/layout/fcm_activity.xml
  app/src/main/res/layout/home_alram.xml
  app/src/main/res/layout/home_fragment.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/style.xml
Labels: 🎨 Design, 🛠 Feat

#56 [MERGE]Feature/team add area
  app/src/main/java/com/example/matching_manager/ui/team/TeamAddActivity.kt
  app/src/main/java/com/example/matching_manager/ui/team/TeamDetailActivity.kt
  app/src/main/java/com/example/matching_manager/ui/team/view/TeamViewModel.kt
  app/src/main/res/layout/team_add_activity.xml
  app/src/main/res/layout/team_add_category.xml
  app/src/main/res/layout/team_calender.xml
  app/src/main/res/layout/team_filter_category.xml
  app/src/main/res/values/string_area.xml
  app/src/main/res/values/string_game.xml
  app/src/main/res/values/string_gender.xml
  app/src/main/res/values/string_level.xml
  app/src/main/res/values/string_spinner.xml
  app/src/main/res/values/string_time.xml
  app/src/main/res/values/strings.xml
Labels: 🛠 Feat

#59 [MERGE]Feature/team add contet
  app/src/main/java/com/example/matching_manager/ui/team/TeamAddActivity.kt
  app/src/main/java/com/example/matching_manager/ui/team/TeamDetailActivity.kt
  app/src/main/java/com/example/matching_manager/ui/team/TeamFragment.kt
  app/src/main/java/com/example/matching_manager/ui/team/TeamListAdapter.kt
  app/src/main/java/com/example/matching_manager/ui/team/view/TeamSharedViewModel.kt
  app/src/main/java/com/example/matching_manager/ui/team/view/TeamViewModel.kt
  app/src/main/res/drawable/button_off.xml
  app/src/main/res/drawable/button_on.xml
  app/src/main/res/drawable/ic_application.png
  app/src/main/res/drawable/ic_recruitment.png
  app/src/main/res/layout/team_detail_activity.xml
  app/src/main/res/layout/team_fragment.xml
  app/src/main/res/layout/team_item.xml
  app/src/main/res/values/strings.xml
Labels: 🛠 Feat

#62 [MERGE] 매치 게시글 수정 및 삭제 시 화면 갱신 오류 해결
  app/src/main/java/com/example/matching_manager/ui/match/MatchDataModel.kt
  app/src/main/java/com/example/matching_manager/ui/match/MatchWritingActivity.kt
  app/src/main/java/com/example/matching_manager/ui/my/MyDeleteDialog.kt
  app/src/main/java/com/example/matching_manager/ui/my/MyFragment.kt
  app/src/main/java/com/example/matching_manager/ui/my/MyMatchDataModel.kt
  app/src/main/java/com/example/matching_manager/ui/my/MyMatchEditActivity.kt
  app/src/main/java/com/example/matching_manager/ui/my/MyMatchRepository.kt
  app/src/main/java/com/example/matching_manager/ui/my/MyMatchRepositoryImpl.kt
  app/src/main/java/com/example/matching_manager/ui/my/MyViewModel.kt
  app/src/main/res/values/strings.xml
Labels: 🛠 Feat, 🩺 Fix

#65 [Merge] 매치 리스트 및 글 작성 시 세부 기능 추가
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/matching_manager/ui/match/MatchDataModel.kt
  app/src/main/java/com/example/matching_manager/ui/match/MatchDetailActivity.kt
  app/src/main/java/com/example/matching_manager/ui/match/MatchFragment.kt
  app/src/main/java/com/example/matching_manager/ui/match/MatchWritingActivity.kt
  app/src/main/java/com/example/matching_manager/ui/my/MyFragment.kt
  app/src/main/java/com/example/matching_manager/ui/my/MyMatchDataModel.kt
  app/src/main/java/com/example/matching_manager/ui/my/MyMatchDetailActivity.kt
  app/src/main/java/com/example/matching_manager/ui/my/MyMatchEditActivity.kt
  app/src/main/res/layout/match_detail_activity.xml
  app/src/main/res/layout/match_fragment.xml
  app/src/main/res/layout/match_writing_activity.xml
  app/src/main/res/layout/my_fragment.xml
  app/src/main/res/layout/my_match_detail_activity.xml
Labels: 🛠 Feat, 🩺 Fix

#67 [Merge] fcm 디바이스간 통신 구현 완료
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/matching_manager/data/remote/FcmRemoteDataSource.kt
  app/src/main/java/com/example/matching_manager/data/repository/FcmRepositoryImpl.kt
  app/src/main/java/com/example/matching_manager/domain/repository/FcmRepository.kt
  app/src/main/java/com/example/matching_manager/fcm/FcmActivity.kt
  app/src/main/java/com/example/matching_manager/fcm/MyFirebaseMessagingService.kt
  app/src/main/java/com/example/matching_manager/fcm/send/Payload.kt
  app/src/main/java/com/example/matching_manager/fcm/send/SendFcmFragment.kt
  app/src/main/java/com/example/matching_manager/fcm/send/SendFcmViewModel.kt
  app/src/main/java/com/example/matching_manager/fcm/send/SendFcmViewModelFactory.kt
  app/src/main/java/com/example/matching_manager/retrofit/RetrofitClient.kt
  app/src/main/java/com/example/matching_manager/retrofit/fcm/FcmRetrofitClient.kt
  app/src/main/java/com/example/matching_manager/ui/home/alarm/AlarmActivity.kt
  app/src/main/java/com/example/matching_manager/ui/home/alarm/AlarmListAdapter.kt
  app/src/main/java/com/example/matching_manager/ui/home/arena/ArenaActivity.kt
  app/src/main/java/com/example/matching_manager/ui/home/arena/detail_dialog/ArenaDetailFragment.kt
  app/src/main/java/com/example/matching_manager/ui/team/TeamDetailActivity.kt
  app/src/main/res/drawable/et_common_background_grey.xml
  app/src/main/res/layout/arena_activity.xml
  app/src/main/res/layout/fcm_activity.xml
  app/src/main/res/layout/send_fcm_fragment.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 📬 API, 🎨 Design, 🛠 Feat

#69 [MERGE] Feat/teamfragment filter
  app/src/main/java/com/example/matching_manager/ui/team/TeamAddActivity.kt
  app/src/main/java/com/example/matching_manager/ui/team/TeamDetailActivity.kt
  app/src/main/java/com/example/matching_manager/ui/team/TeamFragment.kt
  app/src/main/java/com/example/matching_manager/ui/team/TeamItem.kt
  app/src/main/java/com/example/matching_manager/ui/team/bottomsheet/TeamAddCategory.kt
  app/src/main/java/com/example/matching_manager/ui/team/bottomsheet/TeamFilterCategory.kt
  app/src/main/java/com/example/matching_manager/ui/team/view/TeamViewModel.kt
  app/src/main/res/layout/team_detail_activity.xml
  app/src/main/res/layout/team_filter_category.xml
  app/src/main/res/values/string_spinner.xml
Labels: 🛠 Feat

#70 [Merge] Refactoring/GeoCoding to MVVM
  app/src/main/java/com/example/matching_manager/data/repository/GeoRepositoryImpl.kt
  app/src/main/java/com/example/matching_manager/domain/repository/GeoRepository.kt
  app/src/main/java/com/example/matching_manager/domain/usecase/geo/GetGeoLocationUseCase.kt
  app/src/main/java/com/example/matching_manager/ui/home/arena/ArenaViewModel.kt
  app/src/main/java/com/example/matching_manager/ui/home/arena/ArenaViewModelFactory.kt
  app/src/main/java/com/example/matching_manager/util/Utils.kt
Labels: ♻ Refactor

#78 [Merge] Refactoring/login token fcm
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/matching_manager/data/remote/FcmRemoteDataSource.kt
  app/src/main/java/com/example/matching_manager/data/repository/FcmRepositoryImpl.kt
  app/src/main/java/com/example/matching_manager/domain/repository/FcmRepository.kt
  app/src/main/java/com/example/matching_manager/ui/calender/CalendarFragment.kt
  app/src/main/java/com/example/matching_manager/ui/fcm/FcmActivity.kt
  app/src/main/java/com/example/matching_manager/ui/fcm/FcmViewModel.kt
  app/src/main/java/com/example/matching_manager/ui/fcm/FcmViewModelFactory.kt
  app/src/main/java/com/example/matching_manager/ui/fcm/MyFirebaseMessagingService.kt
  app/src/main/java/com/example/matching_manager/ui/fcm/send/Payload.kt
  app/src/main/java/com/example/matching_manager/ui/fcm/send/SendFcmFragment.kt
  app/src/main/java/com/example/matching_manager/ui/fcm/send/SendFcmViewModel.kt
  app/src/main/java/com/example/matching_manager/ui/fcm/send/SendFcmViewModelFactory.kt
  app/src/main/java/com/example/matching_manager/ui/fcm/send/SendType.kt
  app/src/main/java/com/example/matching_manager/ui/home/HomeFragment.kt
  app/src/main/java/com/example/matching_manager/ui/home/arena/ArenaActivity.kt
  app/src/main/java/com/example/matching_manager/ui/home/arena/alarm/AlarmActivity.kt
  app/src/main/java/com/example/matching_manager/ui/home/arena/alarm/AlarmViewModel.kt
  app/src/main/java/com/example/matching_manager/ui/main/MainActivity.kt
  app/src/main/java/com/example/matching_manager/ui/signin/SignInFragment.kt
  app/src/main/java/com/example/matching_manager/ui/team/TeamDetailActivity.kt
  app/src/main/res/layout/fcm_activity.xml
  app/src/main/res/layout/send_fcm_fragment.xml
  app/src/main/res/layout/sign_in_fragment.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: 🛠 Feat, ♻ Refactor

#79 [MARGE] feature/team datail activity
  app/build.gradle
  app/src/main/java/com/example/matching_manager/ui/team/TeamAddActivity.kt
  app/src/main/java/com/example/matching_manager/ui/team/TeamDetailActivity.kt
  app/src/main/res/drawable/btn_background_red_stroke.xml
  app/src/main/res/layout/team_add_activity.xml
  app/src/main/res/layout/team_detail_activity.xml
Labels: 🩺 Fix

#80 [Feat] : 글 작성시 빈칸이 있으면 예외처리
  app/build.gradle
  app/src/main/java/com/example/matching_manager/ui/match/MatchWritingActivity.kt
  app/src/main/java/com/example/matching_manager/ui/team/TeamAddActivity.kt
Labels: 🛠 Feat

#81 [Merge] : 전체적인 UI 및 데이터 불러오는 방식 변경
  app/src/main/java/com/example/matching_manager/domain/usecase/geo/GetGeoLocationUseCase.kt
  app/src/main/java/com/example/matching_manager/ui/match/MatchDataModel.kt
  app/src/main/java/com/example/matching_manager/ui/match/MatchDetailActivity.kt
  app/src/main/java/com/example/matching_manager/ui/match/MatchFragment.kt
  app/src/main/java/com/example/matching_manager/ui/match/MatchListAdapter.kt
  app/src/main/java/com/example/matching_manager/ui/match/MatchRepository.kt
  app/src/main/java/com/example/matching_manager/ui/match/MatchRepositoryImpl.kt
  app/src/main/java/com/example/matching_manager/ui/match/MatchSortBottomSheet.kt
  app/src/main/java/com/example/matching_manager/ui/match/MatchViewModel.kt
  app/src/main/java/com/example/matching_manager/ui/match/MatchWritingActivity.kt
  app/src/main/java/com/example/matching_manager/ui/my/MyDeleteDialog.kt
  app/src/main/java/com/example/matching_manager/ui/my/MyFragment.kt
  app/src/main/java/com/example/matching_manager/ui/my/MyMatchEditActivity.kt
  app/src/main/java/com/example/matching_manager/ui/my/MyMatchListAdapter.kt
  app/src/main/java/com/example/matching_manager/ui/my/MyMatchMenuBottomSheet.kt
  app/src/main/java/com/example/matching_manager/ui/my/MyMatchRepository.kt
  app/src/main/java/com/example/matching_manager/ui/my/MyMatchRepositoryImpl.kt
  app/src/main/java/com/example/matching_manager/ui/my/MyViewModel.kt
  app/src/main/java/com/example/matching_manager/ui/team/TeamAddActivity.kt
  app/src/main/res/drawable/ic_dots.xml
  app/src/main/res/drawable/ic_keyboard_arrow_down.xml
  app/src/main/res/drawable/sort_selector.xml
  app/src/main/res/layout/match_detail_activity.xml
  app/src/main/res/layout/match_fragment.xml
  app/src/main/res/layout/match_item.xml
  app/src/main/res/layout/match_sort_bottom_sheet.xml
  app/src/main/res/layout/match_writing_activity.xml
  app/src/main/res/layout/my_delete_dialog.xml
  app/src/main/res/layout/my_item.xml
  app/src/main/res/layout/my_match_detail_activity.xml
  app/src/main/res/layout/my_match_edit_activity.xml
  app/src/main/res/layout/my_match_menu_bottom_sheet.xml
  app/src/main/res/layout/team_add_activity.xml
  app/src/main/res/layout/team_detail_activity.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 🎨 Design, 🩺 Fix

#85 [Merge] : CRUD 검증, 레이아웃 디테일 수정, 코드 정리
  app/src/main/java/com/example/matching_manager/ui/match/MatchDataModel.kt
  app/src/main/java/com/example/matching_manager/ui/match/MatchDetailActivity.kt
  app/src/main/java/com/example/matching_manager/ui/match/MatchFragment.kt
  app/src/main/java/com/example/matching_manager/ui/match/MatchRepositoryImpl.kt
  app/src/main/java/com/example/matching_manager/ui/match/MatchViewModel.kt
  app/src/main/java/com/example/matching_manager/ui/match/MatchWritingActivity.kt
  app/src/main/java/com/example/matching_manager/ui/match/bottomsheet/MatchFilterCategory.kt
  app/src/main/java/com/example/matching_manager/ui/my/MyFragment.kt
  app/src/main/java/com/example/matching_manager/ui/my/MyMatchDataModel.kt
  app/src/main/java/com/example/matching_manager/ui/my/MyMatchDetailActivity.kt
  app/src/main/java/com/example/matching_manager/ui/my/MyMatchEditActivity.kt
  app/src/main/java/com/example/matching_manager/ui/my/MyMatchMenuBottomSheet.kt
  app/src/main/java/com/example/matching_manager/ui/my/MyMatchRepositoryImpl.kt
  app/src/main/java/com/example/matching_manager/ui/my/MySharedViewModel.kt
  app/src/main/java/com/example/matching_manager/ui/my/MyViewModel.kt
  app/src/main/java/com/example/matching_manager/ui/my/bottomsheet/MyCalender.kt
  app/src/main/java/com/example/matching_manager/ui/my/bottomsheet/MyNumber.kt
  app/src/main/java/com/example/matching_manager/ui/my/bottomsheet/MyTime.kt
  app/src/main/java/com/example/matching_manager/ui/team/TeamListAdapter.kt
  app/src/main/java/com/example/matching_manager/ui/team/view/TeamViewModel.kt
  app/src/main/res/layout/match_detail_activity.xml
  app/src/main/res/layout/match_writing_activity.xml
  app/src/main/res/layout/my_calender.xml
  app/src/main/res/layout/my_match_detail_activity.xml
  app/src/main/res/layout/my_match_edit_activity.xml
  app/src/main/res/layout/my_number.xml
  app/src/main/res/layout/my_time.xml
  app/src/main/res/layout/team_detail_activity.xml
  app/src/main/res/layout/team_item.xml
  app/src/main/res/layout/team_writing_activity.xml
  app/src/main/res/values/strings.xml
Labels: 🩺 Fix

#88 [Merge] Myfragment dialog ui 변경 및 gallery 메모장 ,장소 저장기능
  app/build.gradle
  app/src/main/java/com/example/matching_manager/ui/calender/CalendarFragment.kt
  app/src/main/java/com/example/matching_manager/ui/calender/CalendarListAdapter.kt
  app/src/main/java/com/example/matching_manager/ui/calender/CalendarMemoDecorator.kt
  app/src/main/java/com/example/matching_manager/ui/calender/CalendarMemoDialogFragment.kt
  app/src/main/java/com/example/matching_manager/ui/my/MyFileDialog.kt
  app/src/main/java/com/example/matching_manager/ui/my/MyFragment.kt
  app/src/main/java/com/example/matching_manager/ui/signin/SignInFragment.kt
  app/src/main/res/layout/dialog_edit.xml
  app/src/main/res/values/strings.xml
  settings.gradle
Labels: 🎨 Design
