Repository matching-manager/matching-manager, pull requests merged in 2023-11, with the labels that each got.

#93 [Merge] : 내 게시글 위치 이동 및 내 용병 소집/신청 칸 생성까지만 중간 머지
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/matching_manager/ui/my/MyFragment.kt
  app/src/main/java/com/example/matching_manager/ui/my/MyMatchActivity.kt
  app/src/main/java/com/example/matching_manager/ui/my/MyTeamActivity.kt
  app/src/main/java/com/example/matching_manager/ui/my/MyTeamApplicationFragment.kt
  app/src/main/java/com/example/matching_manager/ui/my/MyTeamRecruitFragment.kt
  app/src/main/java/com/example/matching_manager/ui/my/MyTeamViewPagerAdapter.kt
  app/src/main/res/drawable/ic_arrow_forward.xml
  app/src/main/res/layout/my_fragment.xml
  app/src/main/res/layout/my_match_activity.xml
  app/src/main/res/layout/my_team_activity.xml
  app/src/main/res/layout/my_team_application_fragment.xml
  app/src/main/res/layout/my_team_recruit_fragment.xml
  app/src/main/res/values/themes.xml
Labels: 🛠 Feat, 🩺 Fix

#98 SignIn 디자인 피드백 반영 및 유저 자동 로그인 구현
  app/src/main/java/com/example/matching_manager/data/repository/SharedPreferenceRepositoryImpl.kt
  app/src/main/java/com/example/matching_manager/domain/repository/SharedPreferenceRepository.kt
  app/src/main/java/com/example/matching_manager/domain/usecase/database/AddUserInfoToDataBaseUseCase.kt
  app/src/main/java/com/example/matching_manager/domain/usecase/database/CheckUserInfoToDataBaseUseCase.kt
  app/src/main/java/com/example/matching_manager/domain/usecase/sharedpreference/CheckUserTypeUseCase.kt
  app/src/main/java/com/example/matching_manager/domain/usecase/sharedpreference/SaveUserTypeUseCase.kt
  app/src/main/java/com/example/matching_manager/ui/calender/CalendarFragment.kt
  app/src/main/java/com/example/matching_manager/ui/signin/SignInFragment.kt
  app/src/main/java/com/example/matching_manager/ui/signin/SignInSharedViewModel.kt
  app/src/main/java/com/example/matching_manager/ui/signin/SignInViewModelFactory.kt
  app/src/main/java/com/example/matching_manager/ui/signin/SignUpActivity.kt
  app/src/main/res/anim/blink_animation.xml
  app/src/main/res/drawable/btn_background_sky_blue_fill.xml
  app/src/main/res/drawable/btn_background_sky_blue_stroke.xml
  app/src/main/res/drawable/ic_google.png
  app/src/main/res/drawable/selector_btn_continue_with_google.xml
  app/src/main/res/layout/sign_in_fragment.xml
  app/src/main/res/layout/sign_up_activity.xml
  app/src/main/res/values/strings.xml
Labels: 🎨 Design, 🛠 Feat

#101 아레나,매치,팀페이지 오류 수정 및 기능추가
  app/src/main/java/com/example/matching_manager/ui/home/arena/ArenaActivity.kt
  app/src/main/java/com/example/matching_manager/ui/home/arena/ArenaViewModel.kt
  app/src/main/java/com/example/matching_manager/ui/home/arena/alarm/AlarmActivity.kt
  app/src/main/java/com/example/matching_manager/ui/match/bottomsheet/MatchCalender.kt
  app/src/main/java/com/example/matching_manager/ui/team/TeamListAdapter.kt
  app/src/main/java/com/example/matching_manager/ui/team/TeamWritingActivity.kt
  app/src/main/java/com/example/matching_manager/ui/team/bottomsheet/TeamCalender.kt
  app/src/main/java/com/example/matching_manager/ui/team/viewmodel/TeamSharedViewModel.kt
  app/src/main/java/com/example/matching_manager/ui/team/viewmodel/TeamViewModel.kt
  app/src/main/res/drawable/btn_slide.xml
  app/src/main/res/drawable/img_floating_nor.png
  app/src/main/res/drawable/img_floating_press.png
  app/src/main/res/layout/arena_activity.xml
  app/src/main/res/layout/match_writing_activity.xml
  app/src/main/res/layout/my_match_activity.xml
  app/src/main/res/layout/my_match_edit_activity.xml
  app/src/main/res/layout/my_team_application_edit_activity.xml
  app/src/main/res/layout/my_team_recruit_edit_activity.xml
  app/src/main/res/layout/team_fragment.xml
  app/src/main/res/layout/team_writing_activity.xml
Labels: 🛠 Feat, 🩺 Fix

#104 마이 프래그먼트, 캘린더 프래그먼트 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/matching_manager/ui/calender/CalendarAddDialogFragment.kt
  app/src/main/java/com/example/matching_manager/ui/calender/CalendarEditDialogFragment.kt
  app/src/main/java/com/example/matching_manager/ui/calender/CalendarFragment.kt
  app/src/main/java/com/example/matching_manager/ui/calender/CalendarListAdapter.kt
  app/src/main/java/com/example/matching_manager/ui/calender/CalendarMemoDecorator.kt
  app/src/main/java/com/example/matching_manager/ui/calender/CalendarMemoDialogFragment.kt
  app/src/main/java/com/example/matching_manager/ui/calender/CalendarModel.kt
  app/src/main/java/com/example/matching_manager/ui/calender/CalendarViewModel.kt
  app/src/main/java/com/example/matching_manager/ui/my/MyFragment.kt
  app/src/main/res/drawable/calendar_add_dialog_fragment_button_gray_border.xml
  app/src/main/res/drawable/calendar_add_dialog_fragment_button_green_border.xml
  app/src/main/res/drawable/ic_add.xml
  app/src/main/res/layout/calendar_add_dialog_fragment.xml
  app/src/main/res/layout/calendar_edit_dialog_fragment.xml
  app/src/main/res/layout/calendar_fragment.xml
  app/src/main/res/layout/calendar_memo_dialog_fragment.xml
  app/src/main/res/layout/sign_in_fragment.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/ids.xml
  app/src/main/res/values/strings.xml
Labels: 🛠 Feat

#105 팀 프래그먼트 필터기능 수정
  app/src/main/java/com/example/matching_manager/ui/match/bottomsheet/MatchNumber.kt
  app/src/main/java/com/example/matching_manager/ui/team/TeamFragment.kt
  app/src/main/java/com/example/matching_manager/ui/team/TeamListAdapter.kt
  app/src/main/java/com/example/matching_manager/ui/team/TeamWritingActivity.kt
  app/src/main/java/com/example/matching_manager/ui/team/bottomsheet/TeamAge.kt
  app/src/main/java/com/example/matching_manager/ui/team/bottomsheet/TeamNumber.kt
  app/src/main/java/com/example/matching_manager/ui/team/viewmodel/TeamViewModel.kt
  app/src/main/res/layout/match_writing_activity.xml
  app/src/main/res/layout/team_writing_activity.xml
  app/src/main/res/values/string_spinner.xml
Labels: 🩺 Fix

#106 MyPage 디자인 및 AlarmPage 기능추가
  app/src/main/java/com/example/matching_manager/data/model/UserInfoModel.kt
  app/src/main/java/com/example/matching_manager/data/repository/database/UserInfoRepositoryImpl.kt
  app/src/main/java/com/example/matching_manager/ui/home/arena/alarm/AlarmActivity.kt
  app/src/main/java/com/example/matching_manager/ui/my/MyFragment.kt
  app/src/main/java/com/example/matching_manager/ui/signin/SignInFragment.kt
  app/src/main/java/com/example/matching_manager/ui/signin/SignInSharedViewModel.kt
  app/src/main/java/com/example/matching_manager/ui/signin/UserInformation.kt
  app/src/main/res/drawable/btn_background_black_stroke.xml
  app/src/main/res/drawable/common_profile_card_gradient_background.xml
  app/src/main/res/drawable/ic_baseline_mail_outline_24.xml
  app/src/main/res/drawable/selector_btn_continue_with_google.xml
  app/src/main/res/drawable/test_img_choo.JPG
  app/src/main/res/layout/alarm_activity.xml
  app/src/main/res/layout/my_fragment.xml
  app/src/main/res/values/strings.xml
Labels: 🎨 Design, 🛠 Feat

#108 매치,팀 페이지 글작성 예외처리
  app/src/main/java/com/example/matching_manager/ui/match/MatchDataModel.kt
  app/src/main/java/com/example/matching_manager/ui/match/MatchWritingActivity.kt
  app/src/main/java/com/example/matching_manager/ui/team/TeamWritingActivity.kt
  app/src/main/java/com/example/matching_manager/ui/team/bottomsheet/TeamAge.kt
  app/src/main/res/layout/match_writing_activity.xml
  app/src/main/res/layout/team_writing_activity.xml
Labels: 🛠 Feat

#109 매치 게시글 에딧텍스트 대신 스피너 변경, 뷰카운트 + 챗카운트 기능 추가, 게시글 등록 + 수정 시 이미지 없어도 등록 가능하도록 변경
  app/src/main/java/com/example/matching_manager/ui/match/MatchDetailActivity.kt
  app/src/main/java/com/example/matching_manager/ui/match/MatchFragment.kt
  app/src/main/java/com/example/matching_manager/ui/match/MatchRepository.kt
  app/src/main/java/com/example/matching_manager/ui/match/MatchRepositoryImpl.kt
  app/src/main/java/com/example/matching_manager/ui/match/MatchViewModel.kt
  app/src/main/java/com/example/matching_manager/ui/match/MatchWritingActivity.kt
  app/src/main/java/com/example/matching_manager/ui/match/bottomsheet/MatchSortBottomSheet.kt
  app/src/main/java/com/example/matching_manager/ui/my/MyMatchDetailActivity.kt
  app/src/main/java/com/example/matching_manager/ui/my/MyMatchEditActivity.kt
  app/src/main/java/com/example/matching_manager/ui/my/MyTeamApplicationDetailActivity.kt
  app/src/main/java/com/example/matching_manager/ui/my/MyTeamApplicationEditActivity.kt
  app/src/main/java/com/example/matching_manager/ui/my/MyTeamRecruitDetailActivity.kt
  app/src/main/java/com/example/matching_manager/ui/my/MyTeamRecruitEditActivity.kt
  app/src/main/java/com/example/matching_manager/ui/team/TeamDetailActivity.kt
  app/src/main/java/com/example/matching_manager/ui/team/TeamFragment.kt
  app/src/main/java/com/example/matching_manager/ui/team/TeamWritingActivity.kt
  app/src/main/java/com/example/matching_manager/ui/team/viewmodel/TeamRepository.kt
  app/src/main/java/com/example/matching_manager/ui/team/viewmodel/TeamRepositoryImpl.kt
  app/src/main/java/com/example/matching_manager/ui/team/viewmodel/TeamViewModel.kt
  app/src/main/res/layout/match_fragment.xml
  app/src/main/res/layout/my_match_edit_activity.xml
Labels: 🛠 Feat, 🩺 Fix

#116 HomePage재구성 및 공지사항 페이지 구현
  app/src/main/java/com/example/matching_manager/ui/home/AnnouncementFragment.kt
  app/src/main/java/com/example/matching_manager/ui/home/HomeAnnouncementListAdapter.kt
  app/src/main/java/com/example/matching_manager/ui/home/HomeFragment.kt
  app/src/main/java/com/example/matching_manager/ui/home/HomeMatchListAdapter.kt
  app/src/main/java/com/example/matching_manager/ui/home/HomeViewModel.kt
  app/src/main/java/com/example/matching_manager/ui/home/HomeViewModelFactory.kt
  app/src/main/java/com/example/matching_manager/ui/team/viewmodel/TeamViewModel.kt
  app/src/main/res/drawable/ic_announcement.xml
  app/src/main/res/drawable/ic_arena_color.xml
  app/src/main/res/drawable/ic_arena_color2.xml
  app/src/main/res/drawable/ic_bell.xml
  app/src/main/res/drawable/logo_handshake_green.png
  app/src/main/res/drawable/logo_matching_manager.xml
  app/src/main/res/drawable/rv_home_item_common_background_grey.xml
  app/src/main/res/layout/announcement_fragment.xml
  app/src/main/res/layout/arena_activity.xml
  app/src/main/res/layout/custom_toolbar_sign_up.xml
  app/src/main/res/layout/home_fragment.xml
  app/src/main/res/layout/home_recyclerview_item_announcement.xml
  app/src/main/res/layout/home_recyclerview_item_match.xml
  app/src/main/res/layout/sign_in_fragment.xml
  app/src/main/res/layout/sign_up_activity.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 🎨 Design, 🛠 Feat

#118 Team/Match Detail Page 아이콘추가
  app/src/main/java/com/example/matching_manager/ui/match/MatchDetailActivity.kt
  app/src/main/java/com/example/matching_manager/ui/team/TeamDetailActivity.kt
  app/src/main/res/drawable/ic_application.png
  app/src/main/res/drawable/ic_application.xml
  app/src/main/res/drawable/ic_badminton2.xml
  app/src/main/res/drawable/ic_basketball2.xml
  app/src/main/res/drawable/ic_bodyguard.xml
  app/src/main/res/drawable/ic_bowlingball.xml
  app/src/main/res/drawable/ic_female.xml
  app/src/main/res/drawable/ic_futsal2.xml
  app/src/main/res/drawable/ic_level1.xml
  app/src/main/res/drawable/ic_level2.xml
  app/src/main/res/drawable/ic_level3.xml
  app/src/main/res/drawable/ic_male.xml
  app/src/main/res/drawable/ic_mix.png
  app/src/main/res/drawable/ic_recruitment.png
  app/src/main/res/drawable/ic_recruitment.xml
  app/src/main/res/drawable/ic_soccerball.xml
  app/src/main/res/font/pretendard.xml
  app/src/main/res/font/pretendardblack.ttf
  app/src/main/res/font/pretendardbold.ttf
  app/src/main/res/font/pretendardextrabold.ttf
  app/src/main/res/font/pretendardextralight.ttf
  app/src/main/res/font/pretendardlight.ttf
  app/src/main/res/font/pretendardmedium.ttf
  app/src/main/res/font/pretendardregular.ttf
  app/src/main/res/font/pretendardsemibold.ttf
  app/src/main/res/font/pretendardthin.ttf
  app/src/main/res/layout/alarm_activity.xml
  app/src/main/res/layout/arena_activity.xml
  app/src/main/res/layout/arena_detail_fragment.xml
  app/src/main/res/layout/arena_recyclerview_item.xml
  app/src/main/res/layout/custom_toolbar_sign_up.xml
  app/src/main/res/layout/match_detail_activity.xml
  app/src/main/res/layout/match_fragment.xml
  app/src/main/res/layout/match_writing_activity.xml
  app/src/main/res/layout/my_bookmark_activity.xml
  app/src/main/res/layout/my_fragment.xml
  app/src/main/res/layout/my_match_activity.xml
  app/src/main/res/layout/my_match_detail_activity.xml
  app/src/main/res/layout/my_match_edit_activity.xml
  app/src/main/res/layout/my_team_activity.xml
  app/src/main/res/layout/my_team_application_detail_activity.xml
  app/src/main/res/layout/my_team_recruit_detail_activity.xml
  app/src/main/res/layout/send_fcm_fragment.xml
  app/src/main/res/layout/sign_up_activity.xml
  app/src/main/res/layout/team_detail_activity.xml
  app/src/main/res/layout/team_fragment.xml
  app/src/main/res/layout/team_writing_activity.xml
Labels: 🎨 Design

#119 캘린더에딧프래그먼트 수정 저장기능
  app/src/main/java/com/example/matching_manager/ui/calender/CalendarEditDialogFragment.kt
  app/src/main/java/com/example/matching_manager/ui/calender/CalendarFragment.kt
  app/src/main/java/com/example/matching_manager/ui/calender/CalendarListAdapter.kt
  app/src/main/java/com/example/matching_manager/ui/calender/CalendarModel.kt
  app/src/main/java/com/example/matching_manager/ui/calender/CalendarViewModel.kt
  app/src/main/res/drawable/ic_add.xml
  app/src/main/res/layout/calendar_add_dialog_fragment.xml
  app/src/main/res/layout/calendar_edit_dialog_fragment.xml
  app/src/main/res/layout/calendar_fragment.xml
  app/src/main/res/values/style.xml
Labels: 🩺 Fix

#120 내 게시글 페이지 전체 목록 보이는 오류 수정, 관심 목록 리스트 기능 추가(용병쪽은 수정해야함)
  app/src/main/java/com/example/matching_manager/ui/match/MatchDetailActivity.kt
  app/src/main/java/com/example/matching_manager/ui/my/MyViewModel.kt
  app/src/main/java/com/example/matching_manager/ui/my/bookmark/BookmarkApplicationDataModel.kt
  app/src/main/java/com/example/matching_manager/ui/my/bookmark/BookmarkRecruitDataModel.kt
  app/src/main/java/com/example/matching_manager/ui/my/bookmark/MyBookmarkApplicationFragment.kt
  app/src/main/java/com/example/matching_manager/ui/my/bookmark/MyBookmarkApplicationListAdapter.kt
  app/src/main/java/com/example/matching_manager/ui/my/bookmark/MyBookmarkMatchFragment.kt
  app/src/main/java/com/example/matching_manager/ui/my/bookmark/MyBookmarkMatchListAdapter.kt
  app/src/main/java/com/example/matching_manager/ui/my/bookmark/MyBookmarkRecruitFragment.kt
  app/src/main/java/com/example/matching_manager/ui/my/bookmark/MyBookmarkRecruitListAdapter.kt
  app/src/main/java/com/example/matching_manager/ui/team/TeamDetailActivity.kt
  app/src/main/res/drawable/ic_trash.xml
  app/src/main/res/layout/my_bookmark_application_fragment.xml
  app/src/main/res/layout/my_bookmark_match_fragment.xml
  app/src/main/res/layout/my_bookmark_recruit_fragment.xml
  app/src/main/res/layout/team_detail_activity.xml
Labels: 🛠 Feat, 🩺 Fix

#127 [Fix] 캘린더에딧프래그먼트 기능 수정
  app/build.gradle
  app/src/main/java/com/link_up/matching_manager/ui/calender/CalendarEditDialogFragment.kt
  app/src/main/java/com/link_up/matching_manager/ui/calender/CalendarFragment.kt
  app/src/main/java/com/link_up/matching_manager/ui/calender/CalendarMemoDecorator.kt
  app/src/main/java/com/link_up/matching_manager/ui/calender/CalendarViewModel.kt
  app/src/main/res/layout/calendar_add_dialog_fragment.xml
  app/src/main/res/layout/calendar_edit_dialog_fragment.xml
  app/src/main/res/layout/calendar_fragment.xml
  app/src/main/res/values/string_spinner.xml
  app/src/main/res/values/strings.xml
Labels: 🩺 Fix

#133 매칭/용병 신청 시 메시지가 자동으로 id, number을 포함하게 구현
  app/src/main/java/com/link_up/matching_manager/data/repository/database/UserInfoRepositoryImpl.kt
  app/src/main/java/com/link_up/matching_manager/ui/fcm/send/SendFcmFragment.kt
  app/src/main/java/com/link_up/matching_manager/ui/match/MatchDetailActivity.kt
  app/src/main/java/com/link_up/matching_manager/ui/match/MatchViewModel.kt
  app/src/main/java/com/link_up/matching_manager/ui/match/MatchWritingActivity.kt
  app/src/main/java/com/link_up/matching_manager/ui/my/match/MyMatchActivity.kt
  app/src/main/java/com/link_up/matching_manager/ui/my/my/MyFragment.kt
  app/src/main/java/com/link_up/matching_manager/ui/my/my/MyViewModel.kt
  app/src/main/java/com/link_up/matching_manager/ui/my/team/MyTeamApplicationFragment.kt
  app/src/main/java/com/link_up/matching_manager/ui/my/team/MyTeamRecruitFragment.kt
  app/src/main/java/com/link_up/matching_manager/ui/signin/SignInSharedViewModel.kt
  app/src/main/java/com/link_up/matching_manager/ui/team/TeamDetailActivity.kt
  app/src/main/java/com/link_up/matching_manager/ui/team/TeamWritingActivity.kt
  app/src/main/java/com/link_up/matching_manager/ui/team/view_model/TeamViewModel.kt
  app/src/main/java/com/link_up/matching_manager/util/UserInformation.kt
  app/src/main/res/layout/send_fcm_fragment.xml
  app/src/main/res/values/strings.xml
Labels: 🛠 Feat

#136 홈 화면 기능 마무리
  app/src/main/java/com/link_up/matching_manager/ui/home/home/AnnouncementFragment.kt
  app/src/main/java/com/link_up/matching_manager/ui/home/home/HomeFragment.kt
  app/src/main/java/com/link_up/matching_manager/ui/home/home/HomeViewModel.kt
  app/src/main/java/com/link_up/matching_manager/ui/main/MainActivity.kt
  app/src/main/res/layout/announcement_detail_activity.xml
Labels: 🛠 Feat

#137 Calendar Page 오류 수정 및 약점 보완
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/com/link_up/matching_manager/data/repository/SharedPreferenceRepositoryImpl.kt
  app/src/main/java/com/link_up/matching_manager/domain/repository/SharedPreferenceRepository.kt
  app/src/main/java/com/link_up/matching_manager/domain/usecase/sharedpreference/LoadCalendarDataUseCase.kt
  app/src/main/java/com/link_up/matching_manager/domain/usecase/sharedpreference/SaveCalendarDataUseCase.kt
  app/src/main/java/com/link_up/matching_manager/ui/calender/CalendarEditDialogFragment.kt
  app/src/main/java/com/link_up/matching_manager/ui/calender/CalendarFragment.kt
  app/src/main/java/com/link_up/matching_manager/ui/calender/CalendarListAdapter.kt
  app/src/main/java/com/link_up/matching_manager/ui/calender/CalendarMemoDecorator.kt
  app/src/main/java/com/link_up/matching_manager/ui/calender/CalendarModel.kt
  app/src/main/java/com/link_up/matching_manager/ui/calender/CalendarViewModel.kt
  app/src/main/java/com/link_up/matching_manager/ui/calender/CalendarViewModelFactory.kt
  app/src/main/java/com/link_up/matching_manager/ui/home/arena/ArenaActivity.kt
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/layout/calendar_fragment.xml
  app/src/main/res/layout/calendar_recyclerview_item.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/strings.xml
Labels: 🎨 Design, 🛠 Feat, 🩺 Fix

#139 전체 디자인 수정
  app/src/main/java/com/link_up/matching_manager/ui/calender/CalendarEditDialogFragment.kt
  app/src/main/res/drawable/et_common_background_grey.xml
  app/src/main/res/layout/announcement_fragment.xml
  app/src/main/res/layout/announcement_item.xml
  app/src/main/res/layout/arena_detail_fragment.xml
  app/src/main/res/layout/arena_filter_category.xml
  app/src/main/res/layout/calendar_add_dialog_fragment.xml
  app/src/main/res/layout/calendar_edit_dialog_fragment.xml
  app/src/main/res/layout/home_fragment.xml
  app/src/main/res/layout/match_calender.xml
  app/src/main/res/layout/match_deleted_alert_dialog.xml
  app/src/main/res/layout/match_detail_activity.xml
  app/src/main/res/layout/match_detail_bottom_sheet.xml
  app/src/main/res/layout/match_filter_category.xml
  app/src/main/res/layout/match_number.xml
  app/src/main/res/layout/match_sort_bottom_sheet.xml
  app/src/main/res/layout/match_time.xml
  app/src/main/res/layout/match_writing_activity.xml
  app/src/main/res/layout/my_calender.xml
  app/src/main/res/layout/my_delete_dialog.xml
  app/src/main/res/layout/my_match_detail_activity.xml
  app/src/main/res/layout/my_match_edit_activity.xml
  app/src/main/res/layout/my_number.xml
  app/src/main/res/layout/my_team_application_delete_dialog.xml
  app/src/main/res/layout/my_team_application_detail_activity.xml
  app/src/main/res/layout/my_team_application_edit_activity.xml
  app/src/main/res/layout/my_team_recruit_delete_dialog.xml
  app/src/main/res/layout/my_team_recruit_detail_activity.xml
  app/src/main/res/layout/my_team_recruit_edit_activity.xml
  app/src/main/res/layout/my_time.xml
  app/src/main/res/layout/send_fcm_fragment.xml
  app/src/main/res/layout/sign_up_activity.xml
  app/src/main/res/layout/team_add_category.xml
  app/src/main/res/layout/team_age.xml
  app/src/main/res/layout/team_calender.xml
  app/src/main/res/layout/team_detail_activity.xml
  app/src/main/res/layout/team_filter_category.xml
  app/src/main/res/layout/team_number.xml
  app/src/main/res/layout/team_time.xml
  app/src/main/res/layout/team_writing_activity.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/strings.xml
Labels: 🎨 Design

#144 Dagger2를 사용한 DI(Dependency Injection) 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/link_up/matching_manager/data/di/ApplicationComponent.kt
  app/src/main/java/com/link_up/matching_manager/data/di/ArenaApplication.kt
  app/src/main/java/com/link_up/matching_manager/data/di/DataBaseModule.kt
  app/src/main/java/com/link_up/matching_manager/data/di/NetworkModule.kt
  app/src/main/java/com/link_up/matching_manager/data/di/RepositoryModule.kt
  app/src/main/java/com/link_up/matching_manager/data/remote/FcmRemoteDataSource.kt
  app/src/main/java/com/link_up/matching_manager/data/repository/api/ArenaRepositoryImpl.kt
  app/src/main/java/com/link_up/matching_manager/data/retrofit/AuthorizationInterceptor.kt
  app/src/main/java/com/link_up/matching_manager/data/retrofit/RetrofitClient.kt
  app/src/main/java/com/link_up/matching_manager/data/retrofit/fcm/FcmRetrofitClient.kt
  app/src/main/java/com/link_up/matching_manager/domain/usecase/api/GetArenaInfoUseCase.kt
  app/src/main/java/com/link_up/matching_manager/ui/fcm/send/SendFcmViewModelFactory.kt
  app/src/main/java/com/link_up/matching_manager/ui/home/arena/ArenaActivity.kt
  app/src/main/java/com/link_up/matching_manager/ui/home/arena/ArenaViewModel.kt
  app/src/main/java/com/link_up/matching_manager/ui/home/arena/ArenaViewModelFactory.kt
Labels: 🛠 Feat

#149 상수값 string.xml로 변경
  app/src/main/res/layout/announcement_detail_activity.xml
  app/src/main/res/layout/announcement_fragment.xml
  app/src/main/res/layout/announcement_item.xml
  app/src/main/res/layout/arena_activity.xml
  app/src/main/res/layout/arena_detail_fragment.xml
  app/src/main/res/layout/arena_filter_category.xml
  app/src/main/res/layout/calendar_edit_dialog_fragment.xml
  app/src/main/res/layout/calendar_recyclerview_item.xml
  app/src/main/res/layout/match_calender.xml
  app/src/main/res/layout/match_deleted_alert_dialog.xml
  app/src/main/res/layout/match_detail_activity.xml
  app/src/main/res/layout/match_detail_bottom_sheet.xml
  app/src/main/res/layout/match_filter_category.xml
  app/src/main/res/layout/match_fragment.xml
  app/src/main/res/layout/match_number.xml
  app/src/main/res/layout/match_sort_bottom_sheet.xml
  app/src/main/res/layout/match_time.xml
  app/src/main/res/layout/match_writing_activity.xml
  app/src/main/res/layout/my_application_item.xml
  app/src/main/res/layout/my_bookmark_activity.xml
  app/src/main/res/layout/my_calender.xml
  app/src/main/res/layout/my_delete_dialog.xml
  app/src/main/res/layout/my_fragment.xml
  app/src/main/res/layout/my_match_detail_activity.xml
  app/src/main/res/layout/my_match_edit_activity.xml
  app/src/main/res/layout/my_match_menu_bottom_sheet.xml
  app/src/main/res/layout/my_number.xml
  app/src/main/res/layout/my_team_activity.xml
  app/src/main/res/layout/my_team_application_delete_dialog.xml
  app/src/main/res/layout/my_team_application_detail_activity.xml
  app/src/main/res/layout/my_team_application_edit_activity.xml
  app/src/main/res/layout/my_team_application_menu_bottom_sheet.xml
  app/src/main/res/layout/my_team_recruit_delete_dialog.xml
  app/src/main/res/layout/my_team_recruit_detail_activity.xml
  app/src/main/res/layout/my_team_recruit_edit_activity.xml
  app/src/main/res/layout/my_team_recruit_menu_bottom_sheet.xml
  app/src/main/res/layout/my_time.xml
  app/src/main/res/layout/team_age.xml
  app/src/main/res/layout/team_calender.xml
  app/src/main/res/layout/team_detail_activity.xml
  app/src/main/res/layout/team_filter_category.xml
  app/src/main/res/layout/team_fragment.xml
  app/src/main/res/layout/team_number.xml
  app/src/main/res/layout/team_time.xml
  app/src/main/res/layout/team_writing_activity.xml
  app/src/main/res/values/strings.xml
Labels: 🛠 Feat

#150 전반적인 오류 수정
  app/src/main/java/com/link_up/matching_manager/data/repository/SharedPreferenceRepositoryImpl.kt
  app/src/main/java/com/link_up/matching_manager/data/repository/database/UserInfoRepositoryImpl.kt
  app/src/main/java/com/link_up/matching_manager/domain/repository/SharedPreferenceRepository.kt
  app/src/main/java/com/link_up/matching_manager/domain/usecase/sharedpreference/DeleteUserTypeUseCase.kt
  app/src/main/java/com/link_up/matching_manager/ui/calender/CalendarAddDialogFragment.kt
  app/src/main/java/com/link_up/matching_manager/ui/fcm/send/SendFcmFragment.kt
  app/src/main/java/com/link_up/matching_manager/ui/main/MainActivity.kt
  app/src/main/java/com/link_up/matching_manager/ui/match/MatchDetailActivity.kt
  app/src/main/java/com/link_up/matching_manager/ui/my/bookmark/MyBookmarkApplicationFragment.kt
  app/src/main/java/com/link_up/matching_manager/ui/my/bookmark/MyBookmarkMatchFragment.kt
  app/src/main/java/com/link_up/matching_manager/ui/my/bookmark/MyBookmarkRecruitFragment.kt
  app/src/main/java/com/link_up/matching_manager/ui/my/match/MyMatchActivity.kt
  app/src/main/java/com/link_up/matching_manager/ui/my/match/MyMatchEditActivity.kt
  app/src/main/java/com/link_up/matching_manager/ui/my/my/MyDeleteDialog.kt
  app/src/main/java/com/link_up/matching_manager/ui/my/my/MyFragment.kt
  app/src/main/java/com/link_up/matching_manager/ui/my/my/MyPostViewModel.kt
  app/src/main/java/com/link_up/matching_manager/ui/my/my/MyPostViewModelFactory.kt
  app/src/main/java/com/link_up/matching_manager/ui/my/my/MyViewModel.kt
  app/src/main/java/com/link_up/matching_manager/ui/my/my/MyViewModelFactory.kt
  app/src/main/java/com/link_up/matching_manager/ui/my/team/MyTeamApplicationDeleteDialog.kt
  app/src/main/java/com/link_up/matching_manager/ui/my/team/MyTeamApplicationEditActivity.kt
  app/src/main/java/com/link_up/matching_manager/ui/my/team/MyTeamApplicationFragment.kt
  app/src/main/java/com/link_up/matching_manager/ui/my/team/MyTeamRecruitDeleteDialog.kt
  app/src/main/java/com/link_up/matching_manager/ui/my/team/MyTeamRecruitEditActivity.kt
  app/src/main/java/com/link_up/matching_manager/ui/my/team/MyTeamRecruitFragment.kt
  app/src/main/java/com/link_up/matching_manager/ui/signin/SignInActivity.kt
  app/src/main/java/com/link_up/matching_manager/ui/signin/SignInFragment.kt
  app/src/main/java/com/link_up/matching_manager/ui/team/TeamDetailActivity.kt
  app/src/main/res/layout/my_fragment.xml
Labels: 🩺 Fix

#151 용병 신청 수정 페이지 상단 문구 수정, 처음 앱 시작 시 탭 클릭 후 비정상 페이지 이동 버그 수정, 게시글 수정 시 사진 없어지는 버그 수정, 탭 레이아웃 Calender텍스트 잘림 수정
  app/src/main/java/com/link_up/matching_manager/ui/main/MainActivity.kt
  app/src/main/java/com/link_up/matching_manager/ui/my/match/MyMatchActivity.kt
  app/src/main/java/com/link_up/matching_manager/ui/my/match/MyMatchEditActivity.kt
  app/src/main/java/com/link_up/matching_manager/ui/my/team/MyTeamApplicationEditActivity.kt
  app/src/main/java/com/link_up/matching_manager/ui/my/team/MyTeamRecruitEditActivity.kt
Labels: 🩺 Fix
